import { useState } from 'react';
import './Faq.css';
import { ChevronDown } from 'lucide-react';

const faqData = [
  {
    question: "What makes this AI career coach different?",
    answer: "Our AI career coach provides personalized guidance by analyzing your unique skills and interests, then matching them with real-time market data. Unlike traditional counseling, it provides a dynamic roadmap that evolves with you."
  },
  {
   question:"How do I navigate to the assessment page?",
   answer:"You can get to the assessment page by clicking the 'analysis button' in the navigation bar or the 'Start Your Assessment' button on the home page. Both of these buttons use React Router to change the page."
  },
  {
    question:"Can I see my past assessment results?",
    answer:"Yes, once you are logged in, you can navigate to your profile page to see a history of all the assessments you have completed. The data for these assessments is stored securely in Firebase Firestore."

  },
  {
    question: "How does the assessment work?",
    answer: "The assessment analyzes your self-reported skills, interests, and education level. It uses this information to identify relevant career paths and provides a detailed report on your strengths, growth areas, and a personalized learning path powered by Gemini 2.5 Flash."
  },
   {
    question:"who is eligible for giveing the assessment?",
    answer:"Anyone with a minimum education level of 12th Grade / High School is eligible to take the assessment. The application also includes options for individuals with a Diploma, Undergraduate Degree, and Postgraduate Degree."
  },
  {
    question:"How does the app know which careers to recommend?",
    answer:"The website has a local database of over 250 career paths, each with a list of required skills. It matches the skills you provide to this database to find the most relevant career recommendations for you."
  },
  {
    question: "Is my personal data safe?",
    answer: "Yes, we prioritize your privacy. All user data is securely stored in Firebase and used only to provide your personalized career analysis. We do not share your information with third parties."
  },
 
  {
   question:"How are the career match scores calculated?",
   answer:"The match scores are generated by the Google's Gemini. The AI analyzes the user's profile against the recommended career path and provides a realistic percentage score based on the alignment of skills and interests."
  },
  {
    question:"Who is the target audience for this AI career coach?",
    answer:"The website is designed to help students and professionals. It specifically addresses issues faced by graduates in India, such as a high employability gap and limited awareness of career options."
  }
];

const Faq = () => {
    const [openIndex, setOpenIndex] = useState(null);

    const toggleFaq = (index) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <div className="faq-parent">
          <div className="faq-container">
            <h2 className="faq-title">Frequently Asked Questions</h2>
            <div className="faq-list">
                {faqData.map((item, index) => (
                    <div 
                        key={index} 
                        className={`faq-item ${openIndex === index ? 'open' : ''}`}
                    >
                        <button 
                            className="faq-question-btn" 
                            onClick={() => toggleFaq(index)}
                        >
                            <span>{item.question}</span>
                            <ChevronDown 
                                size={20} 
                                className={`faq-icon ${openIndex === index ? 'rotated' : ''}`} 
                            />
                        </button>
                        <div className="faq-answer-container">
                            <p className="faq-answer-text">{item.answer}</p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
        </div>
    );
};

export default Faq;